spring.application.name=pretetgo
spring.datasource.url=jdbc:mysql://gondola.proxy.rlwy.net:28359/railway
spring.datasource.username=root
spring.datasource.password=aobCnhEmYTmvqoheORdRAlsFbHjqFTuE
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update

spring.servlet.multipart.max-file-size=1GB
spring.servlet.multipart.max-request-size=1GB

server.port=8080
server.forward-headers-strategy=framework

springdoc.swagger-ui.doc-expansion=none

api.key=@pret&go2026!

brevo.api.key=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
brevo.sender.email=meaux.mmi@proton.me
brevo.sender.name=Pret&Go

#spring.mail.host=smtp-relay.brevo.com
#spring.mail.port=587
#spring.mail.username=a68933001@smtp-brevo.com
#spring.mail.password=mZPq3ck2TwbLJHh8
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

#spring.datasource.url=jdbc:mysql://gondola.proxy.rlwy.net:28359/railway
#spring.datasource.url=jdbc:mysql://mysql.railway.internal:3306/railway
#spring.datasource.password=aobCnhEmYTmvqoheORdRAlsFbHjqFTuE